s = input()
print("What is the name of your team?")
print(f"Our name is {s}.")
print("My apologies, I did not understand. What is your team name?")
print(f"We are team {s}.")
print("I am really sorry. Could you please repeat it once again?")
print(f"WE ARE TEAM {s.upper()}!!!")
print("Oh, now I see. Here are your badges. Good luck!")
